SmartSport guide completed
smartsdk/guided-tour pull request #2
Opened 2018-02-26 17:39 UTC by Atlantido

2018-02-26 23:24 UTC, chicco785 requested changes

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +## **What do you need?**
please use canonical markdown

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +## **Introduction**
please use canonical markdown

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +In order to offer a simple and intuitive way to get started with our Smart Spot we have developed an Open Source solution called Smart Spot Starter Kit, which has an obvious educational purpose.  Jus
apply linter, lines should me max 80 chars, see for applied rules:
https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

and here for the linter detected issues: https://travis-ci.org/smartsdk/guided-tour/jobs/346396767

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +
where can it be ordered?

imagine people really need to build the system, how that will be possible?

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +### What is included with The Smart Spot Starter Kit:
this level three is not needed given that there are no other level three in same section

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +
use canonical md, start always with 1. and use proper indentation to ensure numbering is accounted correctly

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +
picture should be intended

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +
picture should be indented

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +
picture should be indented

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +1) First, you need to download the ESP32 toolchain by clicking in this link: [https://dl.espressif.com/dl/esp32\_win32\_msys2\_environment\_and\_toolchain-20180110.zip](https://dl.espressif.com/dl/es
use canonical md numbered list.

```
1. xxx
```

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +~~~
use canonical md code and indent it for proper alignment below the list

1. xxxx

    ```bash
    $ git clone --recursive https://github.com/espressif/esp-idf.git
 
    $ git checkout tags/v3.0-rc1
 
    $ git submodule update –init
    ```

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +~~~
see above

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +
see above

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +
see above

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +
see above

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +
use canonical md

2018-02-26 23:24 UTC, chicco785 commented on docs/sensors/smartspot.md
> +FIWARE ([www.fiware.org](http://www.fiware.org)) is an open platform promoted by the European Commision and maintained by the FIWARE Foundation, where HOP Ubiquitous is Gold Member.
this is a tutorial, so this text is not appropriate,
just shortly describe how to connect the sensor to the proper IoT Agent.

you should also describe how to register a url to be use for physical web interaction

2018-02-27 09:49 UTC, taliaga requested changes

2018-02-27 09:49 UTC, taliaga commented on docs/sensors/smartspot.md
> +## **Getting Started**
I'd suggest adding (windows only) here

2018-02-27 09:49 UTC, taliaga commented on docs/sensors/smartspot.md
> +First, you need to create a WiFi AP with your smartphone for the first connection of the SmartSpot. Once you register in the IoT Agent, you can change the WiFi parameters. This are the default SSID a
There are missing (assumed) steps here, please either add info or links to where that is documented (create ap, register iota, etc)

2018-02-28 10:53 UTC, dancn commented
Hello,
small suggestion: for the MarkDown compliance checking you can use this one-liner:
https://github.com/smartsdk/guided-tour/pull/4/files#diff-04c6e90faac2675aa89e2176d2eec7d8R29

2018-04-09 12:36 UTC, taliaga commented
Hi @Atlantido, content-wise, the changes LGTM.
Last thing I'd suggest is having a look a the CI issues (https://travis-ci.org/smartsdk/guided-tour/jobs/364016350).
Thanks!

2018-04-25 13:18 UTC, chicco785 commented
@Atlantido please lint the markdown as by CI report https://travis-ci.org/smartsdk/guided-tour/jobs/364016350

thx

2018-04-27 09:22 UTC, Atlantido commented
@chicco785 we are adding new content to guide. When we finish adding the new content then we will do pull request

2018-04-30 14:43 UTC, chicco785 commented
hi, by when? we want this to be online before the summit next week :)

thx

2018-04-30 21:28 UTC, Atlantido commented
Tomorrow is a holiday in Spain and this Wednesday in the afternoon or first thing on Monday we will do the pull request

2018-05-08 09:09 UTC, taliaga requested changes

2018-05-08 09:09 UTC, taliaga commented on docs/sensors/smartspot.md
> +~~~
As promised, I'm checking the latest changes. Some comments here:
- I'd put this huge config in a file and reference from it. It bloats the document unnecessarily. If the config already lives somewhere else, just reference it.
- Use single backticks to wrap special words such as environment variable names or filenames: `config.js`
- Minor, but I've never seen those ~~~ to indicate code blocks, I knew of ``` . Does that render fine in the generated docs?. (see a pointer in the README at the root of this project for the doc builder tool)

2018-05-08 09:09 UTC, taliaga commented on docs/sensors/smartspot.md
> +In the following table you can find a config.js file as example for the FIWARE
table?

2018-05-08 09:09 UTC, taliaga commented on docs/sensors/smartspot.md
> +Please, take a look to the docker-compose.yml file, in this one you can find the
Readers will not know where that file is, will they?

2018-05-08 09:09 UTC, taliaga commented on docs/sensors/smartspot.md
> +Add FIWARE security stack Create different docker-composes adapting the
may read better as a list (or bracketed list) as below:
- AA
- BB
- [ ] A
- [ ] B

2018-05-09 09:05 UTC, Atlantido commented
@taliaga In your requested changes you said "may read better as a list (or bracketed list)". I don´t understand what you mean with it can be read better as a list.

2018-05-14 14:37 UTC, chicco785 approved these changes

2018-05-14 14:38 UTC, merged