WIP!!! Add Docs about the Platform
smartsdk/guided-tour pull request #5
Opened 2018-02-28 16:16 UTC by dancn

Just to check the travis build procedure, still some TODO to address before the merge

2018-03-04 12:24 UTC, chicco785 requested changes

2018-03-04 12:24 UTC, chicco785 commented on docs/platform/configuration.md
> +# Configure the SmartSDK Platform Manager
the guided tour is a user perspective, so administration should not be covered

2018-03-04 12:24 UTC, chicco785 commented on docs/platform/usage.md
> +
this content as in the agreed toc should go in the `platform/swarmcluster.md` file

2018-03-05 08:27 UTC, dancn commented on docs/platform/configuration.md
> +# Configure the SmartSDK Platform Manager
Ok, will drop.

2018-03-05 08:27 UTC, dancn commented on docs/platform/usage.md
> +
Ok, will move there!

2018-04-25 13:20 UTC, chicco785 commented
@dancn can you rebase and be sure to merge with the "local" cluster set-up content?
thx!

2018-05-03 14:50 UTC, chicco785 approved these changes

2018-05-03 14:51 UTC, merged