Add services documentation
smartsdk/guided-tour pull request #9
Opened 2018-04-27 14:16 UTC by taliaga

Complete services/contexbroker.md and services/quantumleap.md

2018-04-27 16:18 UTC, chicco785 requested changes

2018-04-27 16:18 UTC, chicco785 commented on docs/services/contextbroker.md
> +If you don't have any, you can simulate some data injection using the [entities-simulator]()
missing link

2018-04-27 16:18 UTC, chicco785 commented on docs/services/contextbroker.md
> +as follows. You need of course to configure the value of ORION_URL with the url
use ``for orion_url

2018-04-27 16:18 UTC, chicco785 commented on docs/services/quantumleap.md
> +
E.g: Last 4 Historical values of `airqualityobserved_0`'s `NO2` and `CO2` attributes.

2018-04-27 16:18 UTC, chicco785 commented on docs/services/quantumleap.md
> +to have something to get started with, you can got to [${GRAFANA_URL}/dashboard/import](${GRAFANA_URL}/dashboard/import)
it's not an actual link, right?

2018-04-27 16:18 UTC, chicco785 commented
minor things, plus some linting issue

2018-04-30 09:21 UTC, taliaga commented on docs/services/quantumleap.md
> +to have something to get started with, you can got to [${GRAFANA_URL}/dashboard/import](${GRAFANA_URL}/dashboard/import)
right, it's just to follow the logic of the explanation.
It could work from the CLI if preceded by `open` command (in MAC for example), but this was not the original intention.

2018-04-30 09:21 UTC, taliaga commented on docs/services/contextbroker.md
> +If you don't have any, you can simulate some data injection using the [entities-simulator]()
fixed

2018-04-30 09:21 UTC, taliaga commented on docs/services/quantumleap.md
> +
changed

2018-04-30 12:47 UTC, chicco785 commented on docs/services/quantumleap.md
> +to have something to get started with, you can got to [${GRAFANA_URL}/dashboard/import](${GRAFANA_URL}/dashboard/import)
so it would be better not to document it as a link.

2018-04-30 14:41 UTC, taliaga commented on docs/services/quantumleap.md
> +to have something to get started with, you can got to [${GRAFANA_URL}/dashboard/import](${GRAFANA_URL}/dashboard/import)
ok, removed!

2018-05-03 12:28 UTC, chicco785 approved these changes

2018-05-03 12:52 UTC, merged